name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ---
  # CI — Continuous Integration
  # Run lint, type check, tests, and build on every push and pull request to main.
  # ---
  ci:
    runs-on: ubuntu-latest

    env:
      PUBLIC_POSTHOG_KEY: 'phc_fake_key_for_ci'
      PUBLIC_POSTHOG_API_HOST: 'https://doesnotmatter.com'
      PUBLIC_USE_REAL_API: false # not used during CI. Only applicable for local development
      PUBLIC_SENTRY_DSN: 'fake-dsn-for-ci'
      PUBLIC_API_BASE_URL: 'https://doesnotmatter.com'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate SvelteKit files
        run: npx svelte-kit sync

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn run check

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build

  # ---
  # CD — Continuous Deployment
  # Trigger a deploy on Render.
  # Only runs on pushes to main (not pull requests).
  # ---
  deploy:
    needs: [ci]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          deploy_url: ${{ secrets.RENDER_STAGING_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"
